language: node_js

# use nodejs v10 LTS
node_js: 
  - 17

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

branches:
  only:
    - hexo # build hexo branch only


script:
  - npm install # install npm files
  - hexo clean # clean static files
  - hexo generate # generate static files
  - echo "bawcat.wiki">./public/CNAME # 生成指定 CNAME
  - echo "google.com, pub-1585951485038445, DIRECT, f08c47fec0942fa0">./public/ads.txt # 写入广告代码
  - cp README.md ./public/
  - cp dongfeng.txt ./public/
  - cp dongfengtest.txt ./public/


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB
  keep-history: true
  target-branch: master
  on:
    branch: hexo
  local-dir: public